# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Nginx installation tasks
  when: nginx_enabled | bool
  tags:
    - setup-all
    - setup-nginx
    - install-all
    - install-nginx
  block:
    - name: Validate Nginx configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Nginx
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Nginx uninstallation tasks
  when: not nginx_enabled | bool
  tags:
    - setup-all
    - setup-nginx
  block:
    - name: Uninstall Nginx
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
