# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Nginx systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ nginx_identifier }}.service"
  register: nginx_service_stat

- name: Uninstall Nginx systemd services and files
  when: nginx_service_stat.stat.exists | bool
  block:
    - name: Ensure Nginx systemd service is stopped
      ansible.builtin.systemd_service:
        name: "{{ nginx_identifier }}"
        state: stopped
        daemon_reload: true

    - name: Ensure Nginx systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ nginx_identifier }}.service"
        state: absent

    - name: Ensure Nginx container network does not exist
      when: nginx_container_network_deletion_enabled
      block:
        - name: Ensure Nginx container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ nginx_container_network }}"
            state: absent
          register: nginx_network_deletion_result

        - name: Ensure Nginx container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ nginx_container_network }}
          register: nginx_network_deletion_result
          changed_when: nginx_container_network in nginx_network_deletion_result.stdout

    - name: Ensure Nginx path does not exist
      ansible.builtin.file:
        path: "{{ nginx_base_path }}"
        state: absent
