# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Nginx settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - nginx_uid
    - nginx_gid
    - nginx_hostname
    - nginx_path_prefix
    - nginx_container_network

# We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
# Knowing that `nginx_path_prefix` does not end with a slash ensures we know how to set
# the default server's location up without having to do "does it end with a slash" checks elsewhere.
- name: Fail if nginx_path_prefix ends with a slash
  ansible.builtin.fail:
    msg: >-
      nginx_path_prefix (`{{ nginx_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/nginx`).
  when: "nginx_path_prefix != '/' and nginx_path_prefix[-1] == '/'"

- name: Fail if Nginx logging level is invalid
  ansible.builtin.fail:
    msg: >-
      nginx_config_log_level must be 'debug', 'info', 'notice', 'warn', 'error', 'crit', 'alert', or 'emerg'
  when: "nginx_config_log_level not in ['debug', 'info', 'notice', 'warn', 'error', 'crit', 'alert', 'emerg']"

- name: Run if Traefik is enabled
  when: nginx_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Nginx are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item.name }}`).
      when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
      with_items:
        - { "name": "nginx_container_labels_traefik_hostname", when: true }
        - { "name": "nginx_container_labels_traefik_path_prefix", when: true }
        - { "name": "nginx_container_labels_traefik_compression_middleware_name", when: "{{ nginx_container_labels_traefik_compression_middleware_enabled }}" }

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `nginx_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if nginx_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          nginx_container_labels_traefik_path_prefix (`{{ nginx_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/nginx`).
      when: "nginx_container_labels_traefik_path_prefix != '/' and nginx_container_labels_traefik_path_prefix[-1] == '/'"
